name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: mymindstorm/setup-emsdk@v12
    - uses: actions/checkout@v3
    - name: make
      run: make
    - uses: actions/upload-artifact@v3
      with:
        name: bbpPairings.exe
        path: bbpPairings.exe
    - uses: actions/upload-artifact@v3
      with:
        name: bbpPairings.wasm
        path: bbpPairings.wasm
